<div class="alert alert-block alert-info">
  <center> <h1> Healthcare accessibility for the elderly in Lisbon </h1> </center> <br>
  <center> <h2> Geospatial Analytics Project </h2> </center> <br>
  <center> <h3> 2025/2026 </h3> </center>
</div>

# Table of Contents

**1. [Importing Libraries and Loading Data](#importing-libraries-and-data)**  
**2. [Loading and Reading Data](#loading-and-reading-data)** 
   - [2.1 Bus stops Visuzalization](#bus-viz)

# 1. Importing Libraries  <a class="anchor" id="importing-libraries-and-data"></a>

In [27]:
#All our libraries
import sqlite3
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from math import ceil
import inspect
import plotly.express as px

#to ommit warnings
import warnings
warnings.filterwarnings('ignore')

#For better resolution plots
%config InlineBackend.figure_format = 'retina' 

#Setting seaborn style
sns.set()

# 2. Open and Reading Data  <a class="anchor" id="loading-and-reading-data"></a>

### Trips

In [ ]:
trips = pd.read_csv("CMET/trips.txt", sep=",")

In [3]:
trips.head(2)

,route_id,service_id,trip_id,pattern_id,trip_headsign,direction_id,shape_id,wheelchair_accessible,bikes_allowed,cars_allowed,calendar_desc
0,1001_0,[F41F4]1,[F41F4]1001_0_1_0600_0629_0_1,1001_0_1,Reboleira (Estação),0,[F41F4]1,0,0,0,NaN
1,1001_0,[F41F4]4,[F41F4]1001_0_1_0600_0629_0_4,1001_0_1,Reboleira (Estação),0,[F41F4]1,0,0,0,NaN

In [4]:
trips.info()

<class 'pandas.DataFrame'>
RangeIndex: 498756 entries, 0 to 498755
Data columns (total 11 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   route_id               498756 non-null  str
 1   service_id             498756 non-null  str
 2   trip_id                498756 non-null  str
 3   pattern_id             498756 non-null  str
 4   trip_headsign          498756 non-null  str
 5   direction_id           498756 non-null  int64
 6   shape_id               498756 non-null  str
 7   wheelchair_accessible  498756 non-null  int64
 8   bikes_allowed          498756 non-null  int64
 9   cars_allowed           498756 non-null  int64
 10  calendar_desc          0 non-null       float64
dtypes: float64(1), int64(4), str(6)
memory usage: 41.9 MB

In [5]:
trips.describe()

,direction_id,wheelchair_accessible,bikes_allowed,cars_allowed,calendar_desc
count,498756.000000,498756.0,498756.0,498756.0,0.0
mean,0.464506,0.0,0.0,0.0,NaN
std,0.498739,0.0,0.0,0.0,NaN
min,0.000000,0.0,0.0,0.0,NaN
25%,0.000000,0.0,0.0,0.0,NaN
50%,0.000000,0.0,0.0,0.0,NaN
75%,1.000000,0.0,0.0,0.0,NaN
max,1.000000,0.0,0.0,0.0,NaN

In [6]:
trips.columns

Index(['route_id', 'service_id', 'trip_id', 'pattern_id', 'trip_headsign',
       'direction_id', 'shape_id', 'wheelchair_accessible', 'bikes_allowed',
       'cars_allowed', 'calendar_desc'],
      dtype='str')

### Stops

In [ ]:
stops = pd.read_csv("CMET/stops.txt", sep=",")

In [5]:
stops.columns

## we get long/lat

Index(['stop_id', 'stop_code', 'stop_name', 'tts_stop_name', 'stop_lat',
       'stop_lon', 'wheelchair_boarding', 'location_type', 'parent_station',
       'platform_code'],
      dtype='str')

In [9]:
stops.head(2)

,stop_id,stop_code,stop_name,tts_stop_name,stop_lat,stop_lon,wheelchair_boarding,location_type,parent_station,platform_code
0,10001,10001,Rua Carlos Manuel Rodrigues Francisco (Escola),Rua Carlos Manuel Rodrigues Francisco ( Escola ),38.754244,-8.959557,0,0,NaN,NaN
1,10002,10002,R Carlos M. Francisco 229 (Escola Monte Novo),Rua Carlos M. Francisco 229 ( Escola Monte Novo ),38.754572,-8.959615,0,0,NaN,NaN

In [10]:
stops.describe()

,stop_id,stop_code,stop_lat,stop_lon,wheelchair_boarding,location_type,parent_station,platform_code
count,12711.000000,12711.000000,12711.000000,12711.000000,12711.0,12711.0,0.0,0.0
mean,112670.699866,112670.699866,38.748224,-9.162225,0.0,0.0,NaN,NaN
std,53434.034509,53434.034509,0.133136,0.164175,0.0,0.0,NaN,NaN
min,10001.000000,10001.000000,38.419378,-9.497247,0.0,0.0,NaN,NaN
25%,71052.500000,71052.500000,38.650363,-9.280339,0.0,0.0,NaN,NaN
50%,120389.000000,120389.000000,38.759473,-9.181842,0.0,0.0,NaN,NaN
75%,160977.500000,160977.500000,38.832991,-9.071188,0.0,0.0,NaN,NaN
max,999999.000000,999999.000000,39.079196,-8.457528,0.0,0.0,NaN,NaN

### Stops_times

In [ ]:
stops_time = pd.read_csv("CMET/stop_times.txt", sep=",")

In [12]:
stops_time.columns

Index(['trip_id', 'arrival_time', 'departure_time', 'stop_id', 'stop_sequence',
       'pickup_type', 'drop_off_type', 'continuous_pickup',
       'continuous_drop_off', 'shape_dist_traveled', 'timepoint'],
      dtype='str')

In [13]:
stops_time.head()

,trip_id,arrival_time,departure_time,stop_id,stop_sequence,pickup_type,drop_off_type,continuous_pickup,continuous_drop_off,shape_dist_traveled,timepoint
0,[F41F4]1001_0_1_0600_0629_0_1,06:20:00,06:20:00,30001,1,0,0,1,1,0.0000,1
1,[F41F4]1001_0_1_0600_0629_0_1,06:21:00,06:21:00,30003,2,0,0,1,1,0.2382,1
2,[F41F4]1001_0_1_0600_0629_0_1,06:21:00,06:21:00,30005,3,0,0,1,1,0.5206,1
3,[F41F4]1001_0_1_0600_0629_0_1,06:22:00,06:22:00,30007,4,0,0,1,1,0.7243,1
4,[F41F4]1001_0_1_0600_0629_0_1,06:22:00,06:22:00,30009,5,0,0,1,1,0.8752,1

In [7]:
stops.columns

Index(['stop_id', 'stop_code', 'stop_name', 'tts_stop_name', 'stop_lat',
       'stop_lon', 'wheelchair_boarding', 'location_type', 'parent_station',
       'platform_code'],
      dtype='str')

## 2.1. Quick visualization to undertsand the Bus stops <a class="anchor" id="bus-viz"></a>

In [ ]:
# Not including the "Margem sul"
lisbon_stops = stops[(stops["stop_lat"] > 38.69) & 
                     (stops["stop_lon"] > -9.5) & 
                     (stops["stop_lon"] < -9.05)]

In [26]:
# Ploting the map
fig = px.scatter_map(
    lisbon_stops,
    lat="stop_lat",
    lon="stop_lon",
    hover_name="stop_name",
    hover_data=["stop_id"],
    zoom=10,
    center={"lat": 38.74, "lon": -9.14},
    title="Carris Stops in Lisbon"
)

fig.update_traces(marker=dict(color="darkgreen", size=8, opacity=0.175))

fig.show()